---
  - name: output from include
    debug: 
      msg: "In append.yml item={{item}}"
  
  - name: check if file exists
    win_stat:
      path: "{{ item }}"
    register: check_file_name

  - name: results
    debug:
      msg: "file {{ check_file_name.stat.exists }}"

  - name: Read file
    ansible.builtin.slurp:
      src: '{{ Outfile }}'
    register: OutfileContents

  - name: Print file content
    ansible.builtin.debug:
      msg: "{{ OutfileContents['content'] | b64decode }}"
  
  - name: if file exists read file
    ansible.builtin.slurp:
      src: '{{ item }}'
    register: itemContents
    when: check_file_name.stat.exists

  - name: if file exists add content
    ansible.windows.win_copy:
      content: | 
        {{ OutfileContents['content'] | b64decode }}
        ##### File Found
        {{ itemContents['content'] | b64decode }}
        dest: "{{ Outfile }}"
    when: check_file_name.stat.exists

  - name: if file missing add content
    ansible.windows.win_copy:
      content: | 
        {{ OutfileContents['content'] | b64decode }}
        ##### File NOT Found
        {{ item }}
      dest: "{{ Outfile }}"
    when: not check_file_name.stat.exists    
    
  