---
  - name: output from include
    debug: 
      msg: "In append.yml item={{item}}"
  
  - name: check if file exists
    win_stat:
      path: "{{ item }}"
    register: check_file_name

  - name: results
    debug:
      msg: "{{ check_file_name }}"

  - name: Read file
    ansible.builtin.slurp:
      src: '{{ Outfile }}'
    register: OutfileContents

  - name: Print file content
    ansible.builtin.debug:
      msg: "{{ OutfileContents['content'] | b64decode }}"

  - name: if file exists add content
    ansible.windows.win_copy:
      content: | 
        {{ OutfileContents['content'] | b64decode }}
        ##### File Found
        {{ item }}
      dest: "{{ Outfile }}"
    when: check_file_name.exists

  - name: if file missing add content
    ansible.windows.win_copy:
      content: | 
        {{ OutfileContents['content'] | b64decode }}
        ##### File NOT Found
        {{ item }}
      dest: "{{ Outfile }}"
    when: not check_file_name.exists    
    
  