---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
# - pge_util.papm_util
#
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookeone in your repo 
      file: playbookone.yml
#
# Separate playbook with ansible facts
#    
# Change the following lines with your playbook
#
- name:  post install g2ao - PB2 
  hosts: all 
  no_log: false
  vars:
    Today: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"
    Path: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}-g2ao.txt"
    Path2: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}-cxya.txt"
    Path3: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}-oxtg.txt"


  tasks:
  ##### G2ao
  - name: Remove files if present
    ansible.windows.win_file:
      path: '{{ item }}'
      state: absent
    with_items:
      - "{{ Path }}"
      - "{{ Path2 }}"
      - "{{ Path3 }}"

  - name: Remote Desktop Users membership
    ansible.windows.win_group_membership:
      name: Remote Desktop Users
      members:
      state: absent
    register: RDU

  - name: Administrators Membership
    ansible.windows.win_group_membership:
      name: Administrators
      members:
      state: absent
    register: Admins
  
  - name: Initiate files
    ansible.windows.win_file:
      path: "{{ item }}"
      state: touch
    with_items:
      - "{{ Path }}"

  - name: Change post file {{ Path }}
    ansible.windows.win_copy:
      content: | 
        ##### Step01 - G2ao
        OS Name and architecture: {{ ansible_os_name }} {{ ansible_architecture2 }}
        IP Addresses: {{ ansible_ip_addresses }}
        Vendor: {{ ansible_system_vendor }}
        --------
        Remote Desktop Users
        {{RDU.members}}
        ---
        Administrators
        {{Admins.members}}
        ---
        ##### Step01 - G2ao
      dest: "{{ Path }}"

  - name: Change post file {{ Path2 }}
    ansible.windows.win_copy:
      content: | 
        ##### Step02 - cxya
        ##### Step02 - cxya
      dest: "{{ Path2 }}"
  
  - name: Change post file {{ Path3 }}
    ansible.windows.win_copy:
      content: | 
        ##### Step03 - oxtg
        ##### Step03 - oxtg
      dest: "{{ Path3 }}"

