--- 
- name:  post=g2ao - main 
  hosts: all 
  vars:
    Today: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"
    OutFile: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}.txt"
    OutFile2: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}_test.txt"

  tasks:
  - name: Touch a file (creates if not present, updates modification time if present)
    ansible.windows.win_file:
      path: C:\Temp\foo.conf
    state: touch
  
  - name: Read file
    ansible.builtin.slurp:
      src: "{{ OutFile }}"
    register: Infile
    
    