--- 
- name:  post=g2ao - main 
  hosts: all 
  vars:
    Today: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"
    OutFile: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}.txt"
    OutFile2: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}_test.txt"

  tasks: 
    - name: Read file
      ansible.builtin.slurp:
        src: "{{ OutFile }}"
      register: Infile
    
    - name: Read file 2
      ansible.builtin.slurp:
        src: "{{ OutFile2 }}"
      register: Infile2