---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
# - pge_util.papm_util
#
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookeone in your repo 
      file: playbookone.yml
#
# Separate playbook with ansible facts
#    
# Change the following lines with your playbook
#
- name: hostname from ansible facts- PlayBook 2 
  hosts: all
  vars:
    HostName: "{{ ansible_hostname }}"
  tasks:
  - debug: 
      msg: "Hostname from ansible facts and variable HostName {{ HostName | upper }}"
    