---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookeone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true

  tasks:
  - name: Copy a folder from GIT
    ansible.windows.win_copy:
      src: payload/
      dest: C:\ansible0\

#Disabling TLS1.0 reg
#[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server]
#"DisabledByDefault"=dword:00000000
#"Enabled"=dword:00000000
#[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client]
#"Enabled"=dword:00000000
#"DisabledByDefault"=dword:00000001
  - name: add a registry value  0
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      name: DisabledByDefault
      data: 1
      type: dword
      state: present

  - name: add a registry value  1
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\S\Client
      name: DisabledByDefault
      data: 1
      type: dword
      state: present
      
  - name: Obtain information about a registry key property Disabling TLS1.0 reg 1
    ansible.windows.win_reg_stat:
      path: HKLM:\\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      name: DisabledByDefault
    register: TLSServer

  - name: Obtain information about a registry key property Disabling TLS1.0 reg 2
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
      name: DisabledByDefault
    register: TLSClient
  
  - name: Print vars
    ansible.builtin.debug:
      msg: TLSServer {{ TLSServer }}
      msg: TLSClient {{ TLSClient }}