--- 
- name:  post=g2ao - main 
  hosts: all 
  vars:
    d1="{{ ansible_date_time.date }}"
  tasks: 
  - debug: var=ansible_date_time
  - debug: msg=" d1 the current date is {{ d1 }}"
  #- debug: msg="the current date is {{ ansible_date_time.date }}"