--- 
- name:  post=g2ao - main 
  hosts: all 
  vars:
    Today: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"
    OutFile: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}.txt"
  tasks: 
  - name: get hotfixes
    win_shell: get_hotfixes 
  - name: Create post file
    ansible.windows.win_copy:
      content: | 
        {{ ansible_hostname }}
        {{ ansible_date_time.date}}
      dest: "{{ OutFile }}"
  - debug: msg="Today is {{ Today }}"
  - debug: msg="OutFile is {{ OutFile }}"