--- 
- name:  post=g2ao - main 
  hosts: all 
  vars:
    Today: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"
    OutFile: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}.txt"
  tasks: 
  - name: Touch a file (creates if not present, updates modification time if present)
    ansible.windows.win_file:
      path: "{{ OutFile }}"
      state: touch  

  - name: Insert line in file
    ansible.builtin.blockinfile:
      path: "{{ OutFile }}"
      block: This is a testfile
    
  - debug: msg="Today is {{ Today }}"
  - debug: msg="OutFile is {{ OutFile }}"