--- 
- name:  post=g2ao - main 
  hosts: all 
  vars:
    Today: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"
    OutFile: "d:\\installs\\{{ansible_hostname | upper}}_{{ Today }}.txt"

  tasks: 
 # - name: get hotfixes
 #   win_shell: get-hotfix
 #   register: Hotfixes

  - name: Create post file
    ansible.windows.win_copy:
      content: | 
        {{ ansible_hostname }}
        {{ ansible_date_time.time}}
        "Hotfixes"
        {{ Hotfixes }}
      dest: "{{ OutFile }}"

  - name: Read file
    ansible.builtin.slurp:
      src: "{{ OutFile }}"
    register: Infile

  - name: Print file content
    ansible.builtin.debug:
      msg: "{{ Infile['content'] | b64decode }}+{{ ansible_hostname }}"
  