--- 
- name:  Win_Ping! - main 
  hosts: all 
  tasks: 
  #- name: Win_Ping! - tasks  
  #  win_ping: 
  
  #- name: Host name
  #  win_shell: $env:computername
  - var: 
    d1: {{ ansible_date_time.date | to_datetime ("%Y%m%d")}}
  - debug: var=ansible_date_time
  - debug: msg="the current date is {{ d1 }}"