--- 
- name:  post=g2ao - main 
  hosts: all 
  vars:
    Today: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"
  tasks: 
  - debug: var=ansible_date_time
  #- debug: var=Today
  - debug: msg="the current date is {{ ansible_date_time.date }}"
  - debug: msg="Today is {{ Today }}"