---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookeone in your repo 
      file: playbookone.yml

  - name: Remove directory structure
    ansible.windows.win_file:
      path: C:\installs
      state: absent
  
  - name: 4. A- sweet 32 registry fix (A.0)
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168
      name: Enabled
      data: 1
      type: dword
      state: present
  
  - name: B -  Disabling TLS 1.0win (B.0)
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      name: DisabledByDefault
      data:1
      type: dword
      state: present
  
  - name: D - MSDT_Vulnerability 
    ansible.windows.win_regedit:
      path: HKCR:\ms-msdt
      state: present

  - name: E - Speculative Execution (E.0)
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
      name: FeatureSettingsOverride
      data: 0
      type: dword
      state: present

  - name: H - WinVerify Trust Signature Validation (H.0)
    ansible.windows.win_regedit:
      path: HKLM:\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config
      name: EnableCertPaddingCheck
      data: 0
      type: dword
      state: present