---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  vars :
    Trellix: Unknown 
    svcname: "trellix"

  gather_facts: true
  tasks:
  #service trkwks s
  #

  - name: Query the Windows service T
    ansible.windows.win_service_info:
      name: '{{ Svcname }}'
    register: service_info

  - name: Modify Trellix var if service is not there
    set_fact: 
      Trellix: "Fail - Service {{ Svcname }} not there"
    when: service_info is not defined
    
  - name: modify Trellix if service_info is Defined
    block:  
      - name: Get service status if service exists Block
        ansible.windows.win_service:
          name: '{{ Svcname }}'
        register: service_state
      
      - name: MOdify Trellix var if service is runningBlock
        set_fact: 
         Trellix: "Pass - Service {{ Svcname }} service is running"
        when: service_state.state == 'running'
        ignore_errors: true
      
      - name: MOdify Trellix var if service exists Block
        set_fact: 
          Trellix: "Fail - Service {{ Svcname }} service is not running"
        when: service_state.state != 'running'
        ignore_errors: true
    
      - name: Trellix display status Block
        debug:
          msg: "Trellix.... {{ Trellix }}  sv.... {{ service_state }}"
    when: service_info is defined
  

  - name: Trellix display status
    debug:
      msg: "Trellix.... {{ Trellix }}  "





  
