---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  vars :
    Svcname: "trkwks"
    Trellixexists: Unknown 
    Trellix: Unknown 
    svc2: "trkwks" #not there
    svcnt: "Unknown" #not there
    svc3: "Unknown" #stopped
    svcst: "Unknown" #not there
  gather_facts: true
  tasks:
  #service trkwks s
  #
  #- name: Query the Windows service T
  #  ansible.windows.win_service_info:
  #    name: '{{ Svcname }}'
  #  register: service_info
#- name: MOdify Trellix var if service exists T
#    ansible.windows.win_service:
#      name: '{{ Svcname }}'
#    register: service_state
#    when: service_info.exists
  #- name: MOdify Trellix var if service exists F
  #  set_fact: 
  #    Trellix: "Fail - {{ Svcname }} service does not exist"
  #  when: service_info.exists == False
  #- name: Trellix
  #  debug:
  #    msg: "Trellix.... {{ Trellix }} SVC...{{ service_info }}"


  - name: collect facts about system services
    ansible.windows.win_service:
      name: '{{ Svcname }}'
    register: service_info
  
  - name: change Trellix if running
    set_fact:
      TrellixEXISTS: Pass
    when: service_info.state=running

  - name: change Trellix if running
    set_fact:
      TrellixEXISTS: FAIL
    when: service_info is not defined

  - name: Debug
    debug:
      msg: TrellixEXISTS {{ TrellixEXISTS }} Trellix {{ Trellix }} service_info = {{ service_info }}


  
