---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  vars :
    Svcname: "trkwks"
    Trellixexists: "False"
    Trellix: "Unknown" 
  gather_facts: true
  tasks:

    
  #service trkwks 
  
  - name: Query the Windows service {{ svcname }}
    ansible.windows.win_service_info:
      name: '{{ Svcname }}'
    register: service_info

  - name: MOdify Trellix var if service exists T
    win_service:
      name: '{{ Svcname }}'
    register: service_status
    when: service_info.exists

  - name: MOdify Trellix var if service exists F
    set_fact: 
      Trellix: "Fail - {{ Svcname }} service does not exist"
    when: service_info.exists == False

  - name: Trellix
    debug:
      msg: "Trellix.... {{ Trellix }} SVC...{{ service_info }}"




  
