---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookeone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true

  tasks:
  - name: Ping an arbitrary Windows server
    ansible.builtin.win_ping:
  - debug:
      msg: "GA Ansible hostname is {{ ansible_hostname }}"
  
  - name: copy a file
    win_copy:
      src: /scriptspwsh/test.ps1
      dest: C:\ansible\renamed-test.ps1
    

