---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookeone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true
  become_method: runas

  tasks:
  - name: Ping an arbitrary Windows server
    ansible.builtin.win_ping:
  - debug:
      msg: "GA Ansible hostname is {{ ansible_hostname }}"
  
  - name: Copy a folder recursively where the source is on the remote host
    ansible.windows.win_copy:
      src: C:\Temp
      dest: C:\ansible
      remote_src: true

  - name: Execute a powershell script on a windows host
    ansible.windows.win_shell: 'c:\temp\helloworld.ps1'
    become: yes
    become_user: Administrator



  - name: Obtain information about a registry key property
    ansible.windows.win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion
      name: CommonFilesDir
    register: common_files_dir

    

