---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  vars :
    svc: Unknown
    svcname: tapisrv
  gather_facts: true
  tasks:

      - name: Check service exists
        ansible.windows.win_service_info:
          name: "{{ svcname }}"
        register: svcinfo

      - name: Check service exists
        ansible.windows.win_service:
          name: "{{ svcname }}"
        register: svcdata
        when: svcinfo.exists == true

      - name: Service there
        set_fact:
          svc: Pass - {{ svcname }} - service is there and state is {{ svcdata.state }}
        when: (svcinfo.exists == true) and (svcdata is defined)

      - name: error service not there
        set_fact:
          svc: FAIL - {{ svcname }} -   service not there
        when: svcinfo.exists == false
      
      - name: svcinfo
        debug:
          msg: "svcinfo {{ svcinfo }} "
        when: svcinfo is defined

      - name: svc
        debug:
          msg: "FINAL:  svc {{ svcname }} {{ svc }}"



  


    







  
