---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
# - pge_util.papm_util
#
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: playbookone.yml
    ansible.builtin.import_tasks:
      # make sure to have playbookeone in your repo 
      file: playbookone.yml
#
# Playbook
#    
- name: PowerShell screipt v1 ALL hosts
  win_shell: 
      $env:computername
  register: hostnm2

- name: Copy a single file where the source is on the remote host
  ansible.windows.win_copy:
    src: C:\temp\output.txt
    dest: C:\temp\output2.txt
    remote_src: true

  #- name: Copy File win_copy g2ao
  #  win_copy:
  #    src: C:\temp\output.txt
  #    dest: C:\temp\output2.txt
  #    remote_src: true