---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#
#collections:
#- pge_util.papm_util
##

  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  vars :
    svc: Unknown
    svc2: Unknown
    svcname: masvc
    
  gather_facts: True
  ignore_errors: True
  
  tasks:
    - name: powershell get service info
      ansible.windows.win_shell: |
        (get-service -name masvc).status
      register: svc

    - name: svc
      debug:
        msg: "FINAL:  svc {{ svcname }} {{ svc }}"
    
    - name: Check service status
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: '{{ ansible_user }}'
        ansible_become_pass: '{{ ansible_password }}'
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      ansible.windows.win_service_info:
        name: "{{ svcname }}"
      register: svc2
    
    - name: svc2
      debug:
        msg: "FINAL:  svc {{ svcname }} {{ svc2 }}"

