---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  vars :
    Svcname: "trkwks"
    Trellixexists: Unknown 
    Trellix: Unknown 
    svc2: "trkwks" #not there
    svcnt: "Unknown" #not there
    svc3: "Unknown" #stopped
    svcst: "Unknown" #not there
  gather_facts: true
  tasks:
  #service trkwks s
  #

  - name: Query the Windows service T
    ansible.windows.win_service_info:
      name: '{{ Svcname }}'
    register: service_info

  - name: Get service status if service exists
    ansible.windows.win_service:
      name: '{{ Svcname }}'
    register: service_state
    when: service_info is defined

  - name: MOdify Trellix var if service is not there
    set_fact: 
      Trellix: "Fail - Service {{ Svcname }} not there"
    when: service_info is not defined
  
  #- name: MOdify Trellix var if service is running
  #  set_fact: 
  #    Trellix: "Pass - Service {{ Svcname }} service is running"
  #  when: service_state.state == Started

  #- name: MOdify Trellix var if service exists F
  #  set_fact: 
  #    Trellix: "Fail - Service {{ Svcname }} service is not running"
  #  when: service_state.state != "Running"
    
  - name: Trellix display status
    debug:
      msg: "Trellix.... {{ Trellix }} SVC...{{ service_state }}"





  
