---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true
  ignore_errors: true
  vars:
    disablesvcs: "['WinHttpAutoProxySvc','spooler','UmRdpService','TapiSrv','snmptrap','msiscsi']"
    regvalkeys: { path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', name: 'EnableLua', value: '0', atatype: 'dword'}
    reg1:
      path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      name: 'EnableLua'
      value: 0
      datatype: dword
    reg2:
      path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      name: 'EnableLua'
      value: 0
      datatype: dword
    
    
 
  tasks:
    - name: Combine regval1 and regval2 into a regvals var
      ansible.builtin.set_fact:
        regvals: "{{ reg1 + reg2 }}"

    - name: rename computer
      debug: 
        msg: rename computer

    - name: Set Static IP
      debug: 
        msg: Set Static IP

    - name: Add to Domain
      debug: 
        msg: Add to Domain

    - name: Change CDROM/DVD to I
      debug: 
        msg: Change CDROM/DVD to I

    # DELL Related software
    - name: Install Dell Openmanage 9.4) if physical
      debug: 
        msg: Install Dell OpenManage 9.4
    
    - name: Install HDLM 8.0 if physical
      debug: 
        msg: Install HDLM 8.0

    - name: Install Emulex One Command if physical
      debug: 
        msg: Install Emulex One Command
    
    - name: Install Mainboard Controller if physical
      debug: 
        msg: Install Mainboard Controller

    - name: Install SysMon Install 1 if physical
      debug: 
        msg: Install SysMon Install 1

    - name: Install MSysMon Install 2 if physical
      debug: 
        msg: Install SysMon Install 2

    - name: Install SysMon Install 3 if physical
      debug: 
        msg: Install SysMon Install 3

    # end of DELL software
    # managed settings - user  rights
    - name: Assign User rights
      debug: 
        msg: Assign User rights

    # modify registry enableLUA 
    # reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
    - name: EnableLUA
      ansible.windows.win_regedit:
        path: "{{ item.path }}"
        name: "{{ item.name }}"
        data: "{{ item.value }}"
        type: "{{ item.datatype }}"
      loop: '{{ regvalkeys }}'

    # run vssadmin.exe resize shadowstorage /on=C: /For=C: /Maxsize=5GB

    - name: Stop and disable Services
      ansible.windows.win_service:
        name: '{{ item }}'
        state: stopped
        start_mode: disabled
      loop: '{{ disablesvcs }}'



 