---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true
  vars:
    svcnames: "['WinHttpAutoProxySvc','spooler','UmRdpService','TapiSrv','snmptrap','msiscsi']"
 
  tasks:
    - name: rename computer
      debug: 
        msg: rename computer

    - name: Set Static IP
      debug: 
        msg: Set Static IP

    - name: Add to Domain
      debug: 
        msg: Add to Domain

    - name: Change CDROM/DVD to I
      debug: 
        msg: Change CDROM/DVD to I

    # DELL Related software
    - name: Install Dell Openmanage 9.4) if physical
      debug: 
        msg: Install Dell OpenManage 9.4
    
    - name: Install HDLM 8.0 if physical
      debug: 
        msg: Install HDLM 8.0

    - name: Install Emulex One Command if physical
      debug: 
        msg: Install Emulex One Command
    
    - name: Install Mainboard Controller if physical
      debug: 
        msg: Install Mainboard Controller

    - name: Install SysMon Install 1 if physical
      debug: 
        msg: Install SysMon Install 1

    - name: Install MSysMon Install 2 if physical
      debug: 
        msg: Install SysMon Install 2

    - name: Install SysMon Install 3 if physical
      debug: 
        msg: Install SysMon Install 3
    # end of DELL software
    # managed settings - user  rights
    - name: Assign User rights
      debug: 
        msg: Assign User rights
    # modify registry enableLUA 
    # reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
    - name: EnableLUA
      debug: 
        msg: EnableLUA

    # run vssadmin.exe resize shadowstorage /on=C: /For=C: /Maxsize=5GB

    - name: Disable Services
      ansible.windows.win_service:
        name: "{{ item }}"
        state: disabled
      register: disabledservices
      loop: '{{ svcnames }}'


 