---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true
  ignore_errors: true
  vars:
    disablesvcs: "['WinHttpAutoProxySvc','spooler','UmRdpService','TapiSrv','snmptrap','msiscsi']"
    regvals:
      - {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', name: 'EnableLua', value: '0', atatype: 'dword'}
      - {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', name: 'EnableLua', value: '0', atatype: 'dword'}

  tasks:
    - name: rename computer
      debug: 
        msg: rename computer

    - name: Set Static IP
      debug: 
        msg: Set Static IP

    - name: Add to Domain
      debug: 
        msg: Add to Domain

    - name: Change CDROM/DVD to I
      debug: 
        msg: Change CDROM/DVD to I

    # DELL Related software
    - name: Only DEll 
      debug: 
        msg: Assign User rights
    # end of DELL software

    # managed settings - user  rights
    - name: Assign User rights
      debug: 
        var: ansible_facts

    # modify registry entries
    - name: EnableLUA
      ansible.windows.win_regedit:
        path: "{{ item.path }}"
        name: "{{ item.name }}"
        data: "{{ item.value }}"
        type: "{{ item.datatype }}"
      loop: '{{ regvals }}'

    # the bottom does not run unless the shadow storage is created
    # run vssadmin.exe resize shadowstorage /on=C: /For=C: /Maxsize=5GB
    
    - name: Stop and disable Services
      ansible.windows.win_service:
        name: '{{ item }}'
        state: stopped
        start_mode: disabled
      loop: '{{ disablesvcs }}'



 