---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true
  tasks:
 

  - name: Create a directory 1
    ansible.windows.win_file:
        path: C:\installs\output
        state: directory
# Sweent 32 registry fix
# "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168" /v Enabled /d 0 /t REG_DWORD /f
# "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168" /v DisabledByDefault /d 1 /t REG_DWORD /f
# "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168/168" /v Enabled /d 0 /t REG_DWORD /f
# "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168/168" /v DisabledByDefault /d 1 /t REG_DWORD /f
  
  - name: Obtain information about a registry key property Sweet32 reg 1
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168
      name: Enabled
    register: SW321

  - name: Obtain information about a registry key property Sweet32 reg 2
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168
      name: DisabledByDefault
    register: SW322

  - name: Obtain information about a registry key property Sweet32 reg 3
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168/168
      name: Enabled
    register: SW323

  - name: Obtain information about a registry key property Sweet32 reg 4
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168/168
      name: DisabledByDefault
    register: SW324

  - name: Define SW32 Conditional Variable
    set_fact:
       SW32: "false"

  - name: Define SW32 Conditional Variable
    set_fact:
       SW32: "true"
    when: sw321.value==1

  #### tls 
  - name: Obtain information about a registry key property Disabling TLS1.0 reg 1
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      name: DisabledByDefault
    register: TLSServer

  - name: Obtain information about a registry key property Disabling TLS1.0 reg 2
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\S\Client
      name: DisabledByDefault
    register: TLSClient

  - name: Define TLS Conditional Variable
    set_fact:
       TLS: "False"

  - name: Define Variable
    set_fact:
       TLS: "true"
    when:  TLSServer.value == 0 and TLSClient.value == 1


  

########################
#     Output file
########################

  - name: "Ansible | Creating a file with content 1"
    win_copy:
     dest: C:\installs\output\log.txt
     content: |
       {{ ansible_hostname }} POST VALIDATION REPORT
       4.a - Sweet32 ...................... {{ SW32 }}
       4.B - Disabling TLS 1.0 (B.0) ...... {{ TLS }}
       HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server = 0 {{ TLSServer.value }}
       HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\S\Client = 1 {{ TLSClient.value }}
       
