---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: false
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:
# 
# task needed for credentials in playbookone.yml
#
  - name: Include task list in play - import - task 1
    ansible.builtin.import_tasks:
      # make sure to have playbookone in your repo 
      file: playbookone.yml

- name: PB2
  hosts: all
  gather_facts: true

  tasks:

  - name: Create a directory 1
    ansible.windows.win_file:
        path: C:\installs\output
        state: directory

  - name: Obtain information about a registry key property Disabling TLS1.0 reg 1
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      name: DisabledByDefault
    register: TLSServer

  - name: Obtain information about a registry key property Disabling TLS1.0 reg 2
    ansible.windows.win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\S\Client
      name: DisabledByDefault
    register: TLSClient

  - set_fact:
    TLS:  "FALSE"

  - set_fact:
    TLS: "TRUE"
    when: |
      TLSServer = 0
      TLScLIENT = 1

  - name: "Ansible | Creating a file with content 2"
    win_copy:
     dest: C:\installs\output\log.txt
     content: |
       {{ ansible_hostname }} POST VALIDATION REPORT
       4.a - Sweet32
       4.B - Disabling TLS 1.0 (B.0) = {{ TLS }}
       HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server = 0 {{ TLSServer.value }}
       HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\S\Client = 1 {{ TLSClient.value }}
       
