---
- name: Gather credentials - PB1
  hosts: all
  gather_facts: true
# prerequisites = have a collections folder in your repo
# with requirements.yml in it with the following:
#---
#collections:
#- pge_util.papm_util
##
  tasks:

  - name: create outputfile 
    ansible.windows.win_file:
      content: | 
        {{ ansible_hostname }}
        -----------------------
      dest: c:\installs\out2.txt